openapi: 3.0.0
info:
  title: "NumberAma API"
  version: "1.0.0"
  contact:
    name: AfricleDev
    email: africle.arts@gmail.com
  description: |
    ## About

    ### Its A Game of Facts 💯 
    A simple trivia API of facts about facts. Great for learning and fun.

    ## Example
    calling the API with a number like 42
    ```bash
    curl -s "{server}/api/trivia/42" \
    -H "Content-Type: application/json" | jq
    ```

    will return something like

    ```json
      {
        "text": "The number 42 is the answer to the question Life, the Universe and Everything",
        "number": 42,
        "found": true,
        "type": "trivia"
      }
    ```

    Also, `/api/:num` is a shorthand for `/api/trivia/:num`

servers:
  - url: https://api.numberama.dev
    description: Production server (hypothetical)
  - url: http://localhost:8888
    description: Localhost server

tags:
  - name: Meta
    description: Metadata
  - name: Facts
    description: Number func facts
paths:
  /:
    get:
      operationId: getMetadata
      summary: Get metadata from the API root
      tags: 
        - Meta
      responses:
        '200':
          description: OK
  
  /trivia/{num}:
    get:
      operationId: getTriviaForNumber
      summary: Get a trivia fact for a number
      tags: 
        - Facts
      parameters:
        - $ref: "#/components/parameters/NumParam"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TriviaResponse"
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/InternalServerError"

  /{num}:
    get:
      $ref: '#/paths/~1trivia~1{num}/get'

  /math/{num}:
    get:
      operationId: getMathFactForNumber
      summary: Get a Math fact for a number
      tags: 
        - Facts
      parameters:
        - $ref: "#/components/parameters/NumParam"
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MathResponse"
        '400':
          $ref: "#/components/responses/BadRequest"
        '500':
          $ref: "#/components/responses/InternalServerError"

components:
  parameters:
    NumParam:
      name: num
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/NumQuery"
      description: The number to search for
      example: 42

    DateParam:
      name: dt
      in: path
      required: true
      schema:
        $ref: "#/components/schemas/DateQuery"
      description: The month and combination (as month-day) to search for
      example: 01-20

  
  schemas:
    NumQuery:
      type: string
      format: int32
      minimum: 0
      maximum: 99999
      example: 42

    DateQuery:
      type: string
      pattern: "[0-9]{1,2}-[0-9]{1,2}"
      example: 01-20

    GameType:
      type: string
      enum:
        - math
        - date
        - trivia

    APIError:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: Bad Request

    TriviaResponse:
      type: object
      required:
        - text
        - number
        - found
        - type
      properties:
        text:
          type: string
          example: The number 42 is the answer to the question Life
        number:
          type: integer
          example: 42
        found:
          type: boolean
          example: true
        type:
          $ref: "#/components/schemas/GameType"
          example: trivia

    MathResponse:
      type: object
      properties:
        text:
          type: string
          example: 5 is the number of platonic solids
        number:
          type: integer
          example: 5
        found:
          type: boolean
          example: true
        type:
          $ref: "#/components/schemas/GameType"
          example: math
  
    DateResponse:
      type: object
      properties:
        text:
          type: string
          example: September 10th is the day in 2001 that Charles Ingram cheats his way into winning one million pounds on a British version of Who Wants to be a Millionaire.
        year:
          type: integer
          pattern: "[0-9]{4}"
          example: 2001
        number:
          type: integer
          example: 254
        found:
          type: boolean
          example: true
        type:
          $ref: "#/components/schemas/GameType"
          example: date

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/APIError"

    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/APIError"


