openapi: 3.0.0
info:
  title: NumberAma API
  version: 1.0.0
  contact:
    name: AfricleDev
    email: africle.arts@gmail.com
  description: |
    ## About

    ### Its A Game of Numbers 💯 
    A simple trivia API of facts about facts. Great for learning and fun.

    ## Example
    calling the API with a number like 42
    ```bash
    curl -s "{server}/api/trivia/42" \
    -H "Content-Type: application/json" | jq
    ```

    will return something like

    ```json
      {
        "text": "The number 42 is the answer to the question Life, the Universe and Everything",
        "number": 42,
        "found": true,
        "type": "trivia"
      }
    ```

    Also, `/api/:num` is a shorthand for `/api/trivia/:num`
servers:
  - url: https://api.numberama.dev
    description: Production server (hypothetical)
  - url: http://localhost:8888
    description: Localhost server
tags:
  - name: Meta
    description: Metadata
  - name: Facts
    description: Number func facts
paths:
  /:
    get:
      operationId: getMetadata
      summary: Get metadata from the API root
      tags:
        - Meta
      responses:
        '200':
          description: OK
  /trivia/{num}:
    get:
      operationId: getTriviaForNumber
      summary: Get a trivia fact for a number
      tags:
        - Facts
      parameters:
        - name: num
          in: path
          required: true
          schema:
            type: string
            format: int32
            minimum: 0
            maximum: 99999
            example: 42
          description: The number to search for
          example: 42
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - text
                  - number
                  - found
                  - type
                properties:
                  text:
                    type: string
                    example: The number 42 is the answer to the question Life
                  number:
                    type: integer
                    example: 42
                  found:
                    type: boolean
                    example: true
                  type:
                    example: trivia
                    type: string
                    enum:
                      - math
                      - date
                      - trivia
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                properties:
                  error:
                    type: string
                    example: Bad Request
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                properties:
                  error:
                    type: string
                    example: Bad Request
  /{num}:
    get:
      tags:
        - Facts
      operationId: getTriviaForNumber
      summary: Get a trivia fact for a number
      parameters:
        - name: num
          in: path
          required: true
          schema:
            type: string
            format: int32
            minimum: 0
            maximum: 99999
            example: 42
          description: The number to search for
          example: 42
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - text
                  - number
                  - found
                  - type
                properties:
                  text:
                    type: string
                    example: The number 42 is the answer to the question Life
                  number:
                    type: integer
                    example: 42
                  found:
                    type: boolean
                    example: true
                  type:
                    example: trivia
                    type: string
                    enum:
                      - math
                      - date
                      - trivia
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                properties:
                  error:
                    type: string
                    example: Bad Request
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                properties:
                  error:
                    type: string
                    example: Bad Request
  /math/{num}:
    get:
      operationId: getMathFactForNumber
      summary: Get a Math fact for a number
      tags:
        - Facts
      parameters:
        - name: num
          in: path
          required: true
          schema:
            type: string
            format: int32
            minimum: 0
            maximum: 99999
            example: 42
          description: The number to search for
          example: 42
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - text
                  - number
                  - found
                  - type
                properties:
                  text:
                    type: string
                    example: 5 is the number of platonic solids
                  number:
                    type: integer
                    example: 5
                  found:
                    type: boolean
                    example: true
                  type:
                    example: math
                    type: string
                    enum:
                      - math
                      - date
                      - trivia
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                properties:
                  error:
                    type: string
                    example: Bad Request
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                properties:
                  error:
                    type: string
                    example: Bad Request
  /date/{when}:
    get:
      operationId: getDateFactForPeriod
      summary: Get a date fact for a period in time
      tags:
        - Facts
      parameters:
        - name: when
          in: path
          required: true
          schema:
            type: string
            pattern: ^(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|[12][0-9]|3[01])|(?:19|20)\d{2})$
          description: >
            The month-day combination or year to search for. Valid usage
            includes:

            - 01-20 (January 20th)

            - 12-31 (December 31st)

            - 2001 (Year 2001)

            - 1999 (Year 1999)


            Some invalid usage includes:  

            - 01-2001 (January 2001st)

            13-01 (invalid month)

            01-32 (invalid day)

            2100 (year out of range)

            999 (incomplete year)


            For optimal results, ensure using a valid month-day or year value as
            the 

            in-built validation might still not catch all invalid dates like
            02-31 (a.k.a Feb, 31st).
          examples:
            month-day:
              value: 01-20
              summary: Search for date facts around the 20th of January
            year:
              value: 2001
              summary: Search for date facts around the year 2001
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - text
                  - year
                  - number
                  - found
                  - type
                properties:
                  text:
                    type: string
                    example: >-
                      September 10th is the day in 2001 that Charles Ingram
                      cheats his way into winning one million pounds on a
                      British version of Who Wants to be a Millionaire.
                  year:
                    type: integer
                    pattern: '[0-9]{4}'
                    example: 2001
                  number:
                    type: integer
                    example: 254
                  found:
                    type: boolean
                    example: true
                  type:
                    example: date
                    type: string
                    enum:
                      - math
                      - date
                      - trivia
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                properties:
                  error:
                    type: string
                    example: Bad Request
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                properties:
                  error:
                    type: string
                    example: Bad Request
components:
  parameters:
    NumParam:
      name: num
      in: path
      required: true
      schema:
        type: string
        format: int32
        minimum: 0
        maximum: 99999
        example: 42
      description: The number to search for
      example: 42
    DateParam:
      name: when
      in: path
      required: true
      schema:
        type: string
        pattern: ^(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|[12][0-9]|3[01])|(?:19|20)\d{2})$
      description: >
        The month-day combination or year to search for. Valid usage includes:

        - 01-20 (January 20th)

        - 12-31 (December 31st)

        - 2001 (Year 2001)

        - 1999 (Year 1999)


        Some invalid usage includes:  

        - 01-2001 (January 2001st)

        13-01 (invalid month)

        01-32 (invalid day)

        2100 (year out of range)

        999 (incomplete year)


        For optimal results, ensure using a valid month-day or year value as
        the 

        in-built validation might still not catch all invalid dates like 02-31
        (a.k.a Feb, 31st).
      examples:
        month-day:
          value: 01-20
          summary: Search for date facts around the 20th of January
        year:
          value: 2001
          summary: Search for date facts around the year 2001
  schemas:
    NumQuery:
      type: string
      format: int32
      minimum: 0
      maximum: 99999
      example: 42
    DateQuery:
      type: string
      pattern: ^(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|[12][0-9]|3[01])|(?:19|20)\d{2})$
    GameType:
      type: string
      enum:
        - math
        - date
        - trivia
    APIError:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          example: Bad Request
    TriviaResponse:
      type: object
      required:
        - text
        - number
        - found
        - type
      properties:
        text:
          type: string
          example: The number 42 is the answer to the question Life
        number:
          type: integer
          example: 42
        found:
          type: boolean
          example: true
        type:
          example: trivia
          type: string
          enum:
            - math
            - date
            - trivia
    MathResponse:
      type: object
      required:
        - text
        - number
        - found
        - type
      properties:
        text:
          type: string
          example: 5 is the number of platonic solids
        number:
          type: integer
          example: 5
        found:
          type: boolean
          example: true
        type:
          example: math
          type: string
          enum:
            - math
            - date
            - trivia
    DateResponse:
      type: object
      required:
        - text
        - year
        - number
        - found
        - type
      properties:
        text:
          type: string
          example: >-
            September 10th is the day in 2001 that Charles Ingram cheats his way
            into winning one million pounds on a British version of Who Wants to
            be a Millionaire.
        year:
          type: integer
          pattern: '[0-9]{4}'
          example: 2001
        number:
          type: integer
          example: 254
        found:
          type: boolean
          example: true
        type:
          example: date
          type: string
          enum:
            - math
            - date
            - trivia
    MetaResponse:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          maxLength: 250
          example: NumberAma is up and running!
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: object
            required:
              - error
            properties:
              error:
                type: string
                example: Bad Request
    InternalServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            type: object
            required:
              - error
            properties:
              error:
                type: string
                example: Bad Request
